# version: '3'

# networks:
#   infrastructure:
#     name: infrastructure
#     external: yes

# services:
#   js-app:
#     image: shantu/js-app:1.0
#     #image: 372951435894.dkr.ecr.us-east-2.amazonaws.com/js-app:latest
#     ports: 
#       - 3000:3000
#     networks:
#       - infrastructure
#   mongodb:
#     image: mongo
#     networks:
#       - infrastructure
#     ports:
#       - 27017:27017
#     environment: 
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=password
#     volumes: 
#       - mongo-data:/data/db
#   mongo-express:
#     image: mongo-express
#     networks:
#       - infrastructure
#     ports:
#       - 8080:8081
#     environment:
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#       - ME_CONFIG_MONGODB_SERVER=mongodb
# volumes: 
#   mongo-data:
#     driver: local

version: '3'

networks:
  infrastructure:
    name: infrastructure
    external: yes

services:
  js-app:
    image: shantu/js-app:1.0
    #image: 372951435894.dkr.ecr.us-east-2.amazonaws.com/js-app:latest
    ports: 
      - 3000:3000
    networks:
      - infrastructure
  mongodb:
    image: mongo
    networks:
      - infrastructure
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: 
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    networks:
      - infrastructure
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes: 
  mongo-data:
    driver: local